create schema library;

CREATE TABLE MEMBERS (
    MemberID INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
    Fname VARCHAR(20),
    Minit CHAR(1),
    Lname VARCHAR(20),
    Address VARCHAR(50),
    PhoneNumber VARCHAR(10),
    Username VARCHAR(15) UNIQUE,
    Password VARCHAR(15),
    Fines DECIMAL(5),
    Is_active BOOLEAN NOT NULL,
    PRIMARY KEY (MemberID)
);

CREATE TABLE ASSOCIATES (
    MemberID INT(4) UNSIGNED NOT NULL,
    Manager BOOLEAN NOT NULL,
    PRIMARY KEY (MemberID),
    FOREIGN KEY (MemberID)
        REFERENCES MEMBERS (MemberID)
);

CREATE TABLE BOOK_DETAILS (
    ISBN VARCHAR(13) NOT NULL,
    Title VARCHAR(100),
    Year VARCHAR(4),
    PRIMARY KEY (ISBN)
);

CREATE TABLE BOOKS (
    ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    ISBN VARCHAR(13) NOT NULL,
    Checked_Out BOOLEAN,
    On_Hold BOOLEAN,
    Date_Out DATE,
    MemberID INT(4) UNSIGNED,
    PRIMARY KEY (ID),
    FOREIGN KEY (ISBN)
        REFERENCES BOOK_DETAILS (ISBN),
    FOREIGN KEY (MemberID)
        REFERENCES MEMBERS (MemberID)
);

CREATE TABLE AUTHORS (
    ISBN VARCHAR(13) NOT NULL,
    AName VARCHAR(50) NOT NULL,
    FOREIGN KEY (ISBN)
        REFERENCES BOOK_DETAILS (ISBN),
    PRIMARY KEY (ISBN , AName)
);

CREATE TABLE KEYWORDS (
    ISBN VARCHAR(13) NOT NULL,
    Keyword VARCHAR(200),
    FOREIGN KEY (ISBN)
        REFERENCES BOOK_DETAILS (ISBN),
    PRIMARY KEY (ISBN , Keyword)
);
	